apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Include the base HelmRelease manifest
resources:
  - helmrelease.yaml

# Optional: Add common labels/annotations for all environments
# commonLabels:
#   app.kubernetes.io/part-of: my-app

# # Optional: Components for reusable patches (e.g., security policies)
# components:
#   - ../../components/security-policies