apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: example-app-1
  namespace: default
spec:
  interval: 1m0s
  ref:
    branch: fluxcd-bootstrap
  url: https://github.com/syedalihussain/example-app-1
