apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: loki-stack
spec:
  install:
    disableWait: true
    timeout: 15m0s
  upgrade:
    disableWait: true
    timeout: 15m0s
  interval: 5m
  dependsOn:
    - name: kube-prometheus-stack
  chart:
    spec:
      version: "2.x"
      chart: loki-stack
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
      interval: 60m
  # https://github.com/grafana/helm-charts/blob/main/charts/loki-stack/values.yaml
  # https://github.com/grafana/loki/blob/main/production/helm/loki/values.yaml
  values:
    compactor:
      extraArgs:
        - -config.expand-env=true
      extraEnvVars:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP

    gateway: 
      extraArgs:
        - -config.expand-env=true
      extraEnvVars:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
    memcachedchunks:
      extraArgs:
        - -config.expand-env=true
      extraEnvVars:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP

    memcachedfrontend:
      extraArgs:
        - -config.expand-env=true
      extraEnvVars:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
    distributor:
      extraArgs:
        - -config.expand-env=true
      extraEnvVars:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
    ingester:
      extraArgs:
        - -config.expand-env=true
      extraEnvVars:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
    querier:
      extraArgs:
      - -config.expand-env=true
      extraEnvVars:
      - name: MY_POD_IP
        valueFrom:
          fieldRef:
            fieldPath: status.podIP
      queryFrontend:
        extraArgs:
        - -config.expand-env=true
        extraEnvVars:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
      queryScheduler:
        extraArgs:
        - -config.expand-env=true
        extraEnvVars:
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
    promtail:
      enabled: true
    loki:
      enabled: true
      isDefault: false
      serviceMonitor:
        enabled: true
        additionalLabels:
          app.kubernetes.io/part-of: kube-prometheus-stack
      config:
        chunk_store_config:
          max_look_back_period: 0s
        table_manager:
          retention_deletes_enabled: true
          retention_period: 12h
        distributor:
          ring:
            kvstore:
              store: memberlist
          memberlist:
            bind_addr:
              - ${MY_POD_IP}
            join_members:
              - 'loki-memberlist'