resources:
- ../../../base
patches:
- target:
    kind: HelmRelease
    name: nodejs-application
  patch: |
    - op: add
      path: /spec/values
      value:
        replicaCount: 1
        image:
          repository: syedalihussain/nodejs-application
          tag: dev-v1.2.0