apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: nodejs-application
  namespace: default
spec:
  interval: 15m
  path: "./deploy"
  prune: true
  sourceRef:
    kind: GitRepository
    name: example-app-1
