apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base/nodejs-application
patches:
- target:
    kind: HelmRelease
    name: nodejs-application
  patch: |
    - op: add
      path: /spec/values
      value:
        replicaCount: 1
        image:
          repository: syedalihussain/nodejs-application
          tag: v1.0.2