apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: example-app-1
  namespace: example-app-1
spec:
  interval: 1m0s
  ref:
    branch: master
  secretRef:
    name: github-token-secret
  url: https://github.com/syedalihussain/example-app-1
