apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: example-app-1
  namespace: flux-system
spec:
  interval: 15m
  path: "./deploy"
  prune: true
  sourceRef:
    kind: GitRepository
    name: example-app-1
