apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nodejs-application
  namespace: default
spec:
  interval: 1m
  chartRef:
    kind: HelmChart
    name: nodejs-application
    namespace: default
  releaseName: nodejs-application
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  test:
    enable: true
  driftDetection:
    mode: enabled
    ignore:
    - paths: ["/spec/replicas"]
      target:
        kind: Deployment
  values:
    replicaCount: 2